### ISSUE TITLE
Unable to parse pubDate

### ISSUE THREAD

**Issue by egeskov** [Opiumtm/PodcastRssClient#1]
Parsing dates like `<pubDate>Fri, 11 Nov 2016 14:36:11 GMT</pubDate>` or `<pubDate>Wed, 07 Dec 2016 00:00:00 EDT</pubDate>` fails and the code falls back to `null`.
These formats should be alright by the [RSS 2.0 specification](https://cyber.harvard.edu/rss/rss.html).

**Comment by Opiumtm** [comment]
I will investigate this

**Comment by Opiumtm** [comment]
@egeskov fixed this issue
https://github.com/Opiumtm/PodcastRssClient/commit/34ee8cf27cf9a639caf24c1223018645ce5212f1

Later I update nuget package as well

**Comment by Opiumtm** [comment]
@egeskov nuget package with bug fix is published

**Comment by egeskov** [comment]
Very nice. I will check it out. Thx.
